{% set name = "paper-qa-pypdf" %}
{% set version = "2025.12.23" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/paper_qa_pypdf-{{ version }}.tar.gz
  sha256: 2c294beacdb4b100f775a16672b75851a1624ec0901b363eaf999598ed39fa4f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - pypdf >=3
    - paper-qa

test:
  imports:
    - paperqa_pypdf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: PaperQA readers implemented using PyPDF
  home: https://github.com/Future-House/paper-qa
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
